version: 2
project_name: pi
builds:
  - id: pi
    main: ./cmd/pi
    binary: pi
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -funcalign=4 -X main.version={{.Version}}
archives:
  - formats: [tar.gz]
    name_template: "pi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
release:
  prerelease: auto
changelog:
  disable: true
