// Package faux provides a scripted, in-memory provider for agent and provider tests.
package faux

import (
	"context"
	"errors"
	"fmt"
	"math/rand/v2"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/OrdalieTech/pi-go/ai"
)

const (
	defaultAPI          ai.API        = "faux"
	defaultProvider     ai.ProviderID = "faux"
	defaultModelID                    = "faux-1"
	defaultModelName                  = "Faux Model"
	defaultBaseURL                    = "http://localhost:0"
	defaultMinTokenSize               = 3
	defaultMaxTokenSize               = 5
)

var defaultUsage = ai.Usage{Cost: ai.Cost{}}

// ModelDefinition describes one model exposed by a Provider.
type ModelDefinition struct {
	ID            string
	Name          *string
	Reasoning     bool
	Input         ai.InputModalities
	Cost          *ai.ModelCostRates
	ContextWindow *float64
	MaxTokens     *float64
}

// TokenSize controls the inclusive range of JavaScript-style token chunk sizes.
type TokenSize struct {
	Min *int
	Max *int
}

// FixedTokenSize configures deterministic chunk boundaries.
func FixedTokenSize(size int) TokenSize {
	return TokenSize{Min: &size, Max: &size}
}

// Options configures a scripted provider.
type Options struct {
	API             ai.API
	Provider        ai.ProviderID
	Models          []ModelDefinition
	TokensPerSecond float64
	TokenSize       TokenSize
	Now             func() int64
}

// AssistantMessageOptions controls fields that differ from the helper defaults.
type AssistantMessageOptions struct {
	StopReason   ai.StopReason
	ErrorMessage *string
	ResponseID   *string
	Timestamp    *int64
}

// ToolCallOptions controls fields generated by ToolCall.
type ToolCallOptions struct {
	ID string
}

// State is a race-safe snapshot of provider invocation state.
type State struct {
	CallCount int64
}

// ResponseFactory resolves a queued response when its request begins streaming.
type ResponseFactory func(
	ctx context.Context,
	requestContext ai.Context,
	options *ai.StreamOptions,
	state State,
	model *ai.Model,
) (*ai.AssistantMessage, error)

// ResponseStep is either an *ai.AssistantMessage, an ai.AssistantMessage, or a ResponseFactory.
type ResponseStep any

// Factory converts a function literal into a queueable ResponseFactory.
func Factory(factory ResponseFactory) ResponseStep {
	return factory
}

// Provider owns faux models, scripted responses, and prompt-cache state.
type Provider struct {
	api             ai.API
	provider        ai.ProviderID
	models          []*ai.Model
	tokensPerSecond float64
	minTokenSize    int
	maxTokenSize    int
	now             func() int64

	mu               sync.Mutex
	pendingResponses []ResponseStep
	callCount        int64
	promptCache      map[string]string
}

// New creates an isolated scripted provider. At most one Options value is accepted.
func New(option ...Options) *Provider {
	if len(option) > 1 {
		panic("faux: New accepts at most one Options value")
	}
	var options Options
	if len(option) == 1 {
		options = option[0]
	}
	now := options.Now
	if now == nil {
		now = wallClockNow
	}

	apiName := options.API
	if apiName == "" {
		apiName = ai.API(randomIDAt(string(defaultAPI), now()))
	}
	providerName := options.Provider
	if providerName == "" {
		providerName = defaultProvider
	}

	requestedMin := defaultMinTokenSize
	requestedMax := defaultMaxTokenSize
	if options.TokenSize.Min != nil {
		requestedMin = *options.TokenSize.Min
	}
	if options.TokenSize.Max != nil {
		requestedMax = *options.TokenSize.Max
	}
	minTokenSize := max(1, min(requestedMin, requestedMax))
	maxTokenSize := max(minTokenSize, requestedMax)

	definitions := options.Models
	if len(definitions) == 0 {
		name := defaultModelName
		contextWindow := float64(128000)
		maxTokens := float64(16384)
		definitions = []ModelDefinition{{
			ID:            defaultModelID,
			Name:          &name,
			Input:         ai.InputModalities{ai.InputText, ai.InputImage},
			Cost:          &ai.ModelCostRates{},
			ContextWindow: &contextWindow,
			MaxTokens:     &maxTokens,
		}}
	}

	models := make([]*ai.Model, 0, len(definitions))
	for _, definition := range definitions {
		name := definition.ID
		if definition.Name != nil {
			name = *definition.Name
		}
		input := definition.Input
		if input == nil {
			input = ai.InputModalities{ai.InputText, ai.InputImage}
		} else {
			input = append(ai.InputModalities(nil), input...)
		}
		cost := ai.ModelCostRates{}
		if definition.Cost != nil {
			cost = *definition.Cost
		}
		contextWindow := float64(128000)
		if definition.ContextWindow != nil {
			contextWindow = *definition.ContextWindow
		}
		maxTokens := float64(16384)
		if definition.MaxTokens != nil {
			maxTokens = *definition.MaxTokens
		}
		models = append(models, &ai.Model{
			ID:            definition.ID,
			Name:          name,
			API:           apiName,
			Provider:      providerName,
			BaseURL:       defaultBaseURL,
			Reasoning:     definition.Reasoning,
			Input:         input,
			Cost:          ai.ModelCost{ModelCostRates: cost},
			ContextWindow: contextWindow,
			MaxTokens:     maxTokens,
		})
	}

	return &Provider{
		api:             apiName,
		provider:        providerName,
		models:          models,
		tokensPerSecond: options.TokensPerSecond,
		minTokenSize:    minTokenSize,
		maxTokenSize:    maxTokenSize,
		now:             now,
		promptCache:     make(map[string]string),
	}
}

// API returns the provider's distinct API identifier.
func (provider *Provider) API() ai.API {
	return provider.api
}

// ProviderID returns the provider identifier placed on models and messages.
func (provider *Provider) ProviderID() ai.ProviderID {
	return provider.provider
}

// Models returns a copy of the model pointer collection.
func (provider *Provider) Models() []*ai.Model {
	return append([]*ai.Model(nil), provider.models...)
}

// GetModel returns the first model when modelID is empty, or the matching model.
func (provider *Provider) GetModel(modelID ...string) *ai.Model {
	if len(modelID) > 1 {
		panic("faux: GetModel accepts at most one model ID")
	}
	if len(modelID) == 0 || modelID[0] == "" {
		return provider.models[0]
	}
	for _, model := range provider.models {
		if model.ID == modelID[0] {
			return model
		}
	}
	return nil
}

// State returns a consistent invocation-state snapshot.
func (provider *Provider) State() State {
	provider.mu.Lock()
	defer provider.mu.Unlock()
	return State{CallCount: provider.callCount}
}

// SetResponses replaces the pending response queue without cloning its elements.
func (provider *Provider) SetResponses(responses []ResponseStep) {
	provider.mu.Lock()
	defer provider.mu.Unlock()
	provider.pendingResponses = append([]ResponseStep(nil), responses...)
}

// AppendResponses appends response steps in FIFO order.
func (provider *Provider) AppendResponses(responses []ResponseStep) {
	provider.mu.Lock()
	defer provider.mu.Unlock()
	provider.pendingResponses = append(provider.pendingResponses, responses...)
}

// PendingResponseCount returns the number of unreserved response steps.
func (provider *Provider) PendingResponseCount() int {
	provider.mu.Lock()
	defer provider.mu.Unlock()
	return len(provider.pendingResponses)
}

// Stream implements ai.StreamFn. Scripted/provider failures are terminal events;
// the returned error is reserved for malformed requests.
func (provider *Provider) Stream(ctx context.Context, request ai.Request) (ai.AssistantMessageEventStream, error) {
	if request.Model == nil {
		return nil, errors.New("faux: model is nil")
	}
	step, hasStep := provider.reserveResponse()
	return provider.streamReserved(ctx, request.Model, request.Context, request.Options, step, hasStep), nil
}

// StreamSimple has the provider-neutral direct stream signature used by agents.
func (provider *Provider) StreamSimple(
	ctx context.Context,
	model *ai.Model,
	requestContext ai.Context,
	options *ai.SimpleStreamOptions,
) (ai.AssistantMessageEventStream, error) {
	if model == nil {
		return nil, errors.New("faux: model is nil")
	}
	var streamOptions *ai.StreamOptions
	if options != nil {
		copy := options.StreamOptions
		streamOptions = &copy
	}
	step, hasStep := provider.reserveResponse()
	return provider.streamReserved(ctx, model, requestContext, streamOptions, step, hasStep), nil
}

func (provider *Provider) reserveResponse() (ResponseStep, bool) {
	provider.mu.Lock()
	defer provider.mu.Unlock()
	provider.callCount++
	if len(provider.pendingResponses) == 0 {
		return nil, false
	}
	step := provider.pendingResponses[0]
	provider.pendingResponses[0] = nil
	provider.pendingResponses = provider.pendingResponses[1:]
	return step, true
}

func (provider *Provider) streamReserved(
	ctx context.Context,
	model *ai.Model,
	requestContext ai.Context,
	options *ai.StreamOptions,
	step ResponseStep,
	hasStep bool,
) ai.AssistantMessageEventStream {
	if ctx == nil {
		ctx = context.Background()
	}
	return func(yield func(ai.AssistantMessageEvent, error) bool) {
		if options != nil && options.OnResponse != nil {
			if err := options.OnResponse(ctx, ai.ProviderResponse{Status: 200, Headers: map[string]string{}}, model); err != nil {
				yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)}, nil)
				return
			}
		}

		if !hasStep {
			message := provider.createErrorMessage(fauxCompatibilityError("No more faux responses queued"), model.ID)
			if err := provider.withUsageEstimate(message, requestContext, options); err != nil {
				message = provider.createErrorMessage(err, model.ID)
			}
			yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: message}, nil)
			return
		}

		resolved, err := resolveResponseStep(ctx, step, requestContext, options, provider.State(), model)
		if err != nil {
			yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)}, nil)
			return
		}
		message, err := cloneMessage(resolved)
		if err != nil {
			yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)}, nil)
			return
		}
		message.API = provider.api
		message.Provider = provider.provider
		message.Model = model.ID
		if err := provider.withUsageEstimate(message, requestContext, options); err != nil {
			yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)}, nil)
			return
		}
		if provider.tokensPerSecond <= 0 {
			events := make([]ai.AssistantMessageEvent, 0, 8)
			collect := func(event ai.AssistantMessageEvent, _ error) bool {
				events = append(events, event)
				return true
			}
			if err := provider.streamWithDeltas(ctx, collect, message); err != nil {
				events = append(events, ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)})
			}
			for _, event := range events {
				if !yield(event, nil) {
					return
				}
			}
			return
		}
		if err := provider.streamWithDeltas(ctx, yield, message); err != nil {
			yield(ai.ErrorEvent{Reason: ai.StopReasonError, Error: provider.createErrorMessage(err, model.ID)}, nil)
		}
	}
}

func resolveResponseStep(
	ctx context.Context,
	step ResponseStep,
	requestContext ai.Context,
	options *ai.StreamOptions,
	state State,
	model *ai.Model,
) (*ai.AssistantMessage, error) {
	switch typed := step.(type) {
	case *ai.AssistantMessage:
		if typed == nil {
			return nil, errors.New("faux: response is nil")
		}
		return typed, nil
	case ai.AssistantMessage:
		return &typed, nil
	case ResponseFactory:
		return typed(ctx, requestContext, options, state, model)
	case func(context.Context, ai.Context, *ai.StreamOptions, State, *ai.Model) (*ai.AssistantMessage, error):
		return typed(ctx, requestContext, options, state, model)
	default:
		return nil, fmt.Errorf("faux: unsupported response step %T", step)
	}
}

// Text creates a faux text block.
func Text(text string) *ai.TextContent {
	return &ai.TextContent{Text: text}
}

// Thinking creates a faux thinking block.
func Thinking(thinking string) *ai.ThinkingContent {
	return &ai.ThinkingContent{Thinking: thinking}
}

// ToolCall creates a faux tool-call block.
func ToolCall(name string, arguments map[string]any, options ...ToolCallOptions) *ai.ToolCall {
	if len(options) > 1 {
		panic("faux: ToolCall accepts at most one ToolCallOptions value")
	}
	id := ""
	if len(options) == 0 {
		id = randomID("tool")
	} else {
		id = options[0].ID
	}
	if arguments == nil {
		arguments = map[string]any{}
	}
	return &ai.ToolCall{ID: id, Name: name, Arguments: arguments}
}

// AssistantMessage creates a faux assistant response from a string, one block,
// or ai.AssistantContent.
func AssistantMessage(content any, options ...AssistantMessageOptions) *ai.AssistantMessage {
	if len(options) > 1 {
		panic("faux: AssistantMessage accepts at most one AssistantMessageOptions value")
	}
	var blocks ai.AssistantContent
	switch typed := content.(type) {
	case string:
		blocks = ai.AssistantContent{Text(typed)}
	case ai.AssistantContentBlock:
		blocks = ai.AssistantContent{typed}
	case ai.AssistantContent:
		blocks = append(ai.AssistantContent(nil), typed...)
	case []ai.AssistantContentBlock:
		blocks = append(ai.AssistantContent(nil), typed...)
	default:
		panic(fmt.Sprintf("faux: unsupported assistant content %T", content))
	}

	settings := AssistantMessageOptions{}
	if len(options) == 1 {
		settings = options[0]
	}
	stopReason := settings.StopReason
	if stopReason == "" {
		stopReason = ai.StopReasonStop
	}
	timestamp := wallClockNow()
	if settings.Timestamp != nil {
		timestamp = *settings.Timestamp
	}
	message := &ai.AssistantMessage{
		Content:      blocks,
		API:          defaultAPI,
		Provider:     defaultProvider,
		Model:        defaultModelID,
		Usage:        defaultUsage,
		StopReason:   stopReason,
		ErrorMessage: cloneString(settings.ErrorMessage),
		ResponseID:   cloneString(settings.ResponseID),
		Timestamp:    timestamp,
	}
	if message.ErrorMessage != nil {
		ai.SetAssistantMessageErrorBeforeTimestamp(message, true)
	}
	return message
}

func (provider *Provider) createErrorMessage(err error, modelID string) *ai.AssistantMessage {
	message := err.Error()
	result := &ai.AssistantMessage{
		Content:      ai.AssistantContent{},
		API:          provider.api,
		Provider:     provider.provider,
		Model:        modelID,
		Usage:        defaultUsage,
		StopReason:   ai.StopReasonError,
		ErrorMessage: &message,
		Timestamp:    provider.now(),
	}
	ai.SetAssistantMessageErrorBeforeTimestamp(result, true)
	return result
}

func (provider *Provider) createAbortedMessage(partial *ai.AssistantMessage) *ai.AssistantMessage {
	aborted := *partial
	aborted.StopReason = ai.StopReasonAborted
	message := "Request was aborted"
	aborted.ErrorMessage = &message
	aborted.Timestamp = provider.now()
	ai.SetAssistantMessageErrorBeforeTimestamp(&aborted, true)
	return &aborted
}

func randomID(prefix string) string {
	return randomIDAt(prefix, wallClockNow())
}

func randomIDAt(prefix string, timestamp int64) string {
	return prefix + ":" + strconv.FormatInt(timestamp, 10) + ":" + strconv.FormatUint(rand.Uint64(), 36)
}

func wallClockNow() int64 {
	return time.Now().UnixMilli()
}

func cloneString(value *string) *string {
	if value == nil {
		return nil
	}
	copy := *value
	return &copy
}

func joinContextParts(parts []string) string {
	return strings.Join(parts, "\n\n")
}

var _ ai.StreamFn = (*Provider)(nil).Stream

// fauxCompatibilityError retains upstream's public provider error text.
func fauxCompatibilityError(message string) error { return errors.New(message) }
